project_id = "ndvwqmoahasggeobwwld"

[functions.send-welcome-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.send-investment-confirmation]
verify_jwt = false

[functions.send-withdrawal-confirmation]
verify_jwt = false

[functions.request-password-reset]
verify_jwt = false

[functions.verify-reset-token]
verify_jwt = false

[functions.complete-password-reset]
verify_jwt = false

[functions.verify-email]
verify_jwt = false

[functions.resend-verification-email]
verify_jwt = true

[functions.send-investment-activation]
verify_jwt = false

[functions.send-withdrawal-status]
verify_jwt = false

[functions.send-withdrawal-request]
verify_jwt = false

[functions.send-profit-notification]
verify_jwt = false

[functions.send-admin-notification]
verify_jwt = false

[functions.update-user-email]
verify_jwt = false

[functions.create-withdrawal]
verify_jwt = true

[functions.request-admin-password-reset]
verify_jwt = false

[functions.admin-login]
verify_jwt = false

[functions.verify-admin-2fa]
verify_jwt = false

[functions.send-referral-notification]
verify_jwt = false

[functions.track-user-login]
verify_jwt = false

[functions.stock-prices]
verify_jwt = false
