project_id = "ndvwqmoahasggeobwwld"

[functions.send-welcome-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.send-investment-confirmation]
verify_jwt = false

[functions.send-withdrawal-confirmation]
verify_jwt = false